const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    grayText: "#A4A4A4",
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  primary: '#C6E8FF',
  secondary: '#F2F6FC',
  tint: '#0B289A',
  inputBackground: "#F2F2F4",
  buttonTextPrimary: "#073250",
  white: '#FFFFFF',
  black: '#000000',
  lightGrey: '#FAFAFA',
  midGray: '#F5F5F5',
  darkGray: "#8E8E8E",
  focus: '#F2F6FC',
  pink: "#F9EDFF",
  cyan: "#DEF6F5",
  cyanLight: "#F2FBFF",
  blue: "#3165A3",
  blueLight: "#F1F8FF",
  dotsGray: '#E2E2E2',
  buttonGray: "#F8F8F8",
  bottomBarGray: "#F1F2F2",
  textGrayLight: "#CBCBCB",
  textGrayMedium: "#9C9C9C",
  green: "#19A516",
  red: "#A51616",
  redLight: "#FFF2F2",
  orangeLight: "#FFF8F2",
  purple: "#AD0FB0",
  brown: "#A69465",
  brownLight: "#FFF6DE",
  purpleLight: "#FFF2FF",
  greenLight: "#F2FFF6",
  borderColor: "#EDEDED"
};
